### ISSUE TITLE
unusually slow vulkan/glsl compared to cuda

### ISSUE THREAD

**Issue by KestutisMa** [Glavnokoman/vuh#23] opened 2018-11-01 07:00 UTC
Same algorithm using CUDA (v10) is ~4 times faster even when using double-precision data types than glsl/vulkan (v1.1.89, glslang v7.9.2888) using single-precision (float).
~~Another observation: for some reason when using single-precision error accumulates in cuda code and results differ after several hundreds of iterations (double precision wroks ok). Though single-precision version of glsl/vulkan code gives good results.~~ Fixed by adding "f" suffix to constants in kernel (*by advice in https://devtalk.nvidia.com/default/topic/1043602/cuda-programming-and-performance/solved-cuda-single-precision-code-accumulates-error-while-glsl-vulkan-works-why-/*)
 Here is code: https://drive.google.com/open?id=1Q72ERuCLypzvRjAzSZ3a3bLD9k2JEGuW
I tried with run_async.

**Comment by KestutisMa** [comment] 2018-11-02 19:08
Thanks, I agree that suggested libraries are good, but program execute kernels 10000 times in a for cycle, and measure only that cycles time (not including data copy and function to add kernel to program), which is about 4s. So I think in this case it is quite accurate. In a for cycle there are only two kernels calls and a one line of a simple expression to calculate one variable (time is the same if I comment that out).
I am thinking how to profile spir-v kernel.

**Comment by Glavnokoman** [comment] 2018-11-13 22:48
I can reproduce your numbers with nvidia vulkan driver, but using the integrated intel card it all looks much better. Will dig more into it.
```bash
> export VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json 
> ./vuh_NobleVulkan 
mem size =  107 MB

Time required for execution 10000 times: 2.85859 seconds.
noble_outfile_V.binary wrote
Done
> export VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/intel_icd.x86_64.json 
> ./vuh_NobleVulkan 
mem size =  107 MB

Time required for execution 10000 times: 0.27639 seconds.
noble_outfile_V.binary wrote
Done
```

**Comment by Glavnokoman** [comment] 2018-11-14 10:52
I tried it on another machine with a radeon card
```bash
> export VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/radeon_icd.x86_64.json 
> ./vuh_NobleVulkan 
mem size =  107 MB
WARNING: radv is not a conformant vulkan implementation, testing use only.

Time required for execution 10000 times: 0.595042 seconds.
noble_outfile_V.binary wrote
Done
```

**Comment by Glavnokoman** [comment] 2018-11-14 21:08
check if this branch resolves your issue: [branch]( https://github.com/Glavnokoman/vuh/tree/issue/23_slow_vulkan_cuda) .
There is a fix on a Vuh side, so you will need to recompile the lib.
I also modified your program a bit and added it to `doc/examples/noble_vuh`. It is mostly warm-up added to mask out compilation times, and async calls replaced by the fully sync ones, cause now sync calls are much cheaper, and your calls were in fact fully sync anyway.
Please check it works for you.

**Comment by KestutisMa** [comment] 2018-11-17 08:59
I added Wall time measurement, which sometimes were more than cpu time, as I mentioned in second post. Now 10 000 iterations took:

- 0.75 s wall time, 0.35 s cpu time (integrated gpu on intel 4670K cpu)
- 0.38 s wall time, 0.38 s cpu time (nvidia geforce gtx 960)

also I tried kernels with empty main() function:
- 0.54 s wall time, 0.30 s cpu time (integrated gpu on intel 4670K cpu)
- 0.32 s wall time, 0.32 s cpu time (nvidia geforce gtx 960)

Results show that there is big improvement in new version (0.38 s vs 5.1s before) on nvidia! Thank you. Also wall and cpu time now  is the same on nvidia (before wall time was more than cpu), but differs on intel gpu.

Also I improved cuda performance twice (0.3 -> 0.15s, 10000 iter.) by adding "f" suffix to constants in kernel. But same didn't improve performance in glsl. 

Wall time using empty kernels (0.32 s) doesn't differ much from normal kernels (0.38 s). (In cuda version using empty kernels is much faster - 0.06s). So seems that you are correct about API and I will try to contact nvidia and report about problem with their driver vulkan api performance.

which radeon card were you using?

**Comment by Glavnokoman** [comment] 2018-11-19 17:55
AMD Radeon R7 M465
```bash
WARNING: radv is not a conformant vulkan implementation, testing use only.
Time required for execution 10000 times: 0.259685 seconds.
 ```
Intel GPU timing fluctuates between 0.25 and 0.70 seconds - very unstable.
It would be very difficult to beat CUDA in this kind of benchmarks since it has access to both GPU and CPU sides of the code, so better optimization potential, and those guys invested quite some effort into reducing the kernel call latencies. I do have couple of ideas though for Vuh but not sure of their potential yet.
For now I am going to close this ticket if you do not mind. Thanks for driving my attention to the problem.

**Closed by Glavnokoman** 2018-11-19 17:55 UTC
Labels: performance
